
FROM debian:latest
RUN apt-get update && apt-get install -y\
    valgrind \
    build-essential \
    gdb \
    vim \
    git \
    iproute2\
    tcpdump\
    inetutils-traceroute\
    inetutils-ping
